In [3]:
from mlscratch.imports import  *
from mlscratch.linear_algebra import BackSub

In [4]:
A = np.array([[1, -3, 4], [0, 1, 2], [0, 0, 1]])
print('A: \n', A, '\n\n')

b = np.array([7, 2, 5])
print('b: \n', b)

BackSub.back_sub(A, b)

A: 
 [[ 1 -3  4]
 [ 0  1  2]
 [ 0  0  1]] 


b: 
 [7 2 5]


array([-37.,  -8.,   5.])

In [5]:
A = np.array([[1, -3, 4], [1, 1, 2], [0, 0, 1]])
print('A: \n', A, '\n\n')

b = np.array([7, 2, 5])
print('b: \n', b)

BackSub.back_sub(A, b)

A: 
 [[ 1 -3  4]
 [ 1  1  2]
 [ 0  0  1]] 


b: 
 [7 2 5]


Exception: Not upper triangular

In [6]:
A = np.array([[1, -3], [1, 1], [0, 0]])
print('A: \n', A, '\n\n')

b = np.array([7, 2])
print('b: \n', b)

BackSub.back_sub(A, b)

A: 
 [[ 1 -3]
 [ 1  1]
 [ 0  0]] 


b: 
 [7 2]


Exception: Not a square matrix

In [7]:
A = np.array([[1, -3, 7], [0, 1, 4], [0, 0, 0]])
print('A: \n', A, '\n\n')

b = np.array([1, 0, 5])
print('b: \n', b)

BackSub.back_sub(A, b)

A: 
 [[ 1 -3  7]
 [ 0  1  4]
 [ 0  0  0]] 


b: 
 [1 0 5]


Exception: Diagonal element is zero