In [3]:
from mlscratch.imports import  *
from mlscratch.linear_algebra import MatrixSolve

In [4]:
A = np.random.randn(16).reshape((4, 4))
print(A)

[[-0.60565445  1.2210773  -1.64714572  1.09568985]
 [ 0.07577056  0.6646772  -0.91320763  0.19471493]
 [-0.8000844   0.58272057  0.13969997  1.02299635]
 [ 1.30941355 -1.44459543 -0.8121858   0.80501764]]


In [5]:
b = np.random.randn(4).reshape((4, 1))
print(b)

[[-1.61901955e-01]
 [-7.50105092e-01]
 [ 2.76261814e+00]
 [ 2.21037965e-03]]


In [6]:
MatrixSolve.solve(A, b)

[[-0.60565445  1.2210773  -1.64714572  1.09568985 -0.16190195]
 [ 0.          0.81744039 -1.11927423  0.33179149 -0.77035988]
 [ 0.         -1.03035252  2.31561991 -0.42443684  2.9764946 ]
 [ 0.          1.19535078 -4.37328394  3.17387854 -0.34781861]]
[[-0.60565445  1.2210773  -1.64714572  1.09568985 -0.16190195]
 [ 0.          0.81744039 -1.11927423  0.33179149 -0.77035988]
 [ 0.          0.          0.90481732 -0.00622628  2.00548527]
 [ 0.          0.         -2.73655871  2.68869671  0.77868589]]
[[-6.05654447e-01  1.22107730e+00 -1.64714572e+00  1.09568985e+00
  -1.61901955e-01]
 [ 0.00000000e+00  8.17440393e-01 -1.11927423e+00  3.31791494e-01
  -7.70359878e-01]
 [ 0.00000000e+00  0.00000000e+00  9.04817319e-01 -6.22628354e-03
   2.00548527e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.66986574e+00
   6.84414030e+00]]
[[-6.05654447e-01  1.22107730e+00 -1.64714572e+00  1.09568985e+00
  -1.61901955e-01]
 [ 0.00000000e+00  8.17440393e-01 -1.11927423e+00  3.31791494e-01
  

array([0.99863113, 1.07611893, 2.23409319, 2.56347733])

In [7]:
np.linalg.solve(A, b).ravel()

array([0.99863113, 1.07611893, 2.23409319, 2.56347733])